// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV7x05gyZjUOyTOM1-Ut46-XjFKGI-Ms8',
    appId: '1:197399421932:web:af962403ae04f06b4a16c9',
    messagingSenderId: '197399421932',
    projectId: 'pinoki-14a04',
    authDomain: 'pinoki-14a04.firebaseapp.com',
    storageBucket: 'pinoki-14a04.firebasestorage.app',
    measurementId: 'G-G5M46VPKR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpLTNTo8CWb0xdeV0751RmWHhALtMNuVU',
    appId: '1:197399421932:android:b503c78cb6149e794a16c9',
    messagingSenderId: '197399421932',
    projectId: 'pinoki-14a04',
    storageBucket: 'pinoki-14a04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtGpKK8yyu2dN8hJYQBTD4Vm5PObDYEIo',
    appId: '1:197399421932:ios:4cc9b63e665c79c44a16c9',
    messagingSenderId: '197399421932',
    projectId: 'pinoki-14a04',
    storageBucket: 'pinoki-14a04.firebasestorage.app',
    iosBundleId: 'com.example.pinoki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtGpKK8yyu2dN8hJYQBTD4Vm5PObDYEIo',
    appId: '1:197399421932:ios:4cc9b63e665c79c44a16c9',
    messagingSenderId: '197399421932',
    projectId: 'pinoki-14a04',
    storageBucket: 'pinoki-14a04.firebasestorage.app',
    iosBundleId: 'com.example.pinoki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV7x05gyZjUOyTOM1-Ut46-XjFKGI-Ms8',
    appId: '1:197399421932:web:db0741aac8dd1ddc4a16c9',
    messagingSenderId: '197399421932',
    projectId: 'pinoki-14a04',
    authDomain: 'pinoki-14a04.firebaseapp.com',
    storageBucket: 'pinoki-14a04.firebasestorage.app',
    measurementId: 'G-BJN9YSHZCX',
  );
}
